#================================================
# Macro file to test IAEAphsp writer
#================================================
/control/verbose 0
/run/verbose 0
/tracking/verbose 0
/event/verbose 0
#

/action/IAEAphspWriter/namePrefix  psf_z
/action/IAEAphspWriter/zphsp      10.1 cm 
#
/goss/geom/worldXY   25.0 cm
/goss/geom/worldZ   100.0 cm
#
/my_phys/setList  EMStandardPhysics_option4
#
/run/initialize
#
/run/setCut          0.1 mm
#
/gun/particle  gamma
/my_beam/kinE    10.0 MeV
/my_beam/DE       5.0 MeV
/my_beam/X0   0.2 cm
/my_beam/DX   4.0 cm
/my_beam/Y0   0.2 cm
/my_beam/DY   4.0 cm
/my_beam/Z0   0.2 cm
/my_beam/verbose  0
#
/run/beamOn        10000000
/run/printProgress  1000
#
